/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.8.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { UncheckedDenom, UncheckedDepositInfo, Empty, ProposeMessage, Binary, Status, Coin, Addr } from "./types";
import { Config, DepositInfoResponse, HooksResponse } from "./DaoPreProposeSingle.types";
export interface DaoPreProposeSingleReadOnlyInterface {
    contractAddress: string;
    proposalModule: () => Promise<Addr>;
    dao: () => Promise<Addr>;
    config: () => Promise<Config>;
    depositInfo: ({ proposalId }: {
        proposalId: number;
    }) => Promise<DepositInfoResponse>;
    proposalSubmittedHooks: () => Promise<HooksResponse>;
    queryExtension: ({ msg }: {
        msg: Empty;
    }) => Promise<Binary>;
}
export declare class DaoPreProposeSingleQueryClient implements DaoPreProposeSingleReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    proposalModule: () => Promise<Addr>;
    dao: () => Promise<Addr>;
    config: () => Promise<Config>;
    depositInfo: ({ proposalId }: {
        proposalId: number;
    }) => Promise<DepositInfoResponse>;
    proposalSubmittedHooks: () => Promise<HooksResponse>;
    queryExtension: ({ msg }: {
        msg: Empty;
    }) => Promise<Binary>;
}
export interface DaoPreProposeSingleInterface extends DaoPreProposeSingleReadOnlyInterface {
    contractAddress: string;
    sender: string;
    propose: ({ msg }: {
        msg: ProposeMessage;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateConfig: ({ depositInfo, openProposalSubmission }: {
        depositInfo?: UncheckedDepositInfo;
        openProposalSubmission: boolean;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    withdraw: ({ denom }: {
        denom?: UncheckedDenom;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    extension: ({ msg }: {
        msg: Empty;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    addProposalSubmittedHook: ({ address }: {
        address: string;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    removeProposalSubmittedHook: ({ address }: {
        address: string;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    proposalCompletedHook: ({ newStatus, proposalId }: {
        newStatus: Status;
        proposalId: number;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class DaoPreProposeSingleClient extends DaoPreProposeSingleQueryClient implements DaoPreProposeSingleInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    propose: ({ msg }: {
        msg: ProposeMessage;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateConfig: ({ depositInfo, openProposalSubmission }: {
        depositInfo?: UncheckedDepositInfo;
        openProposalSubmission: boolean;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    withdraw: ({ denom }: {
        denom?: UncheckedDenom;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    extension: ({ msg }: {
        msg: Empty;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    addProposalSubmittedHook: ({ address }: {
        address: string;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    removeProposalSubmittedHook: ({ address }: {
        address: string;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    proposalCompletedHook: ({ newStatus, proposalId }: {
        newStatus: Status;
        proposalId: number;
    }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
