/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.9.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import {InstantiateMsg, ExecuteMsg, QueryMsg, MigrateMsg, NullableValidatorInfo, Uint128, ValidatorInfo} from "./ProxyBitcoin.types";
export interface ProxyBitcoinReadOnlyInterface {
  contractAddress: string;
  validatorInfo: ({
    valAddr
  }: {
    valAddr: string;
  }) => Promise<NullableValidatorInfo>;
}
export class ProxyBitcoinQueryClient implements ProxyBitcoinReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.validatorInfo = this.validatorInfo.bind(this);
  }

  validatorInfo = async ({
    valAddr
  }: {
    valAddr: string;
  }): Promise<NullableValidatorInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      validator_info: {
        val_addr: valAddr
      }
    });
  };
}